apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: elastalert-ocp
  name: elastalert-ocp
  namespace: openshift-logging
spec:
  replicas: 1
  selector:
    app: elastalert-ocp
    deploymentconfig: elastalert-ocp
  template:
    metadata:
      labels:
        app: elastalert-ocp
        deploymentconfig: elastalert-ocp
    spec:
      containers:
      - image: openshift-logging/elastalert-ocp:latest
        imagePullPolicy: Always
        name: elastalert-ocp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/curator/keys
          name: logging-elasticsearch
          readOnly: true
        - mountPath: /opt/elastalert/config
          name: elastalert-config
        - mountPath: /opt/elastalert/rules
          name: elastalert-rules
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: logging-elasticsearch
        secret:
          defaultMode: 420
          items:
          - key: admin-ca
            path: ca
          - key: admin-cert
            path: cert
          - key: admin-key
            path: key
          secretName: logging-elasticsearch
      - configMap:
          defaultMode: 420
          name: elastalert-config
        name: elastalert-config
      - configMap:
          defaultMode: 420
          name: elastalert-rules
        name: elastalert-rules
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - elastalert-ocp
      from:
        kind: ImageStreamTag
        name: elastalert-ocp:latest
        namespace: openshift-logging
    type: ImageChange
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastalert-config
  namespace: openshift-logging
data:
  elastalert_config.yaml: |
    # This is the folder that contains the rule yaml files
    # Any .yaml file will be loaded as a rule
    rules_folder: /opt/elastalert/rules

    #
    scan_subdirectories: false

    # How often ElastAlert will query elasticsearch
    # The unit can be anything from weeks to seconds
    run_every:
      minutes: 1

    # ElastAlert will buffer results from the most recent
    # period of time, in case some log sources are not in real time
    buffer_time:
      minutes: 15

    # The elasticsearch hostname for metadata writeback
    # Note that every rule can have it's own elasticsearch host
    # en0 on docker host
    es_host: logging-es

    # The elasticsearch port
    es_port: 9200

    # The index on es_host which is used for metadata storage
    # This can be a unmapped index, but it is recommended that you run
    # elastalert-create-index to set a mapping
    writeback_index: elastalert_status

    # If an alert fails for some reason, ElastAlert will retry
    # sending the alert until this time period has elapsed
    alert_time_limit:
      days: 2

    use_ssl: True
    verify_certs: True

    # Secrets must be mounted!
    ca_certs: /etc/curator/keys/ca
    client_cert: /etc/curator/keys/cert
    client_key: /etc/curator/keys/key

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastalert-rules
  namespace: openshift-logging
data:
  events-alert.yaml: |
    # elastalert-test-rule --config /opt/elastalert/config/elastalert_config.yaml --formatted-output --alert /tmp/test.yaml
    name: New Openshift Event

    type: frequency
    
    index: .all*
    
    num_events: 1
    
    realert:
      minutes: 0

    timeframe:
      minutes: 2
      # hours: 18
    
    filter:
    - query:
        bool:
          must:
          - exists:
              field: "kubernetes.event.type"
          must_not:
          - match:
              kubernetes.event.type: Normal
          - match:
              kubernetes.event.type: Info
              
    alert:
    - ms_teams:
        ms_teams_webhook_url: https://outlook.office.com/webhook/2a34a818-6745-4096-97bf-5b26caf63f7f@a8eec281-aaa3-4dae-ac9b-9a398b9215e7/IncomingWebhook/5e349056dee94949887b4625d70432f1/cb742064-a9b6-4b62-bb88-f7fe3a905112
        alert_text_type: alert_text_only
        ms_teams_alert_summary: "At least one non-normal Openshift Event was registered."
        alert_text: |
          <b>No. of Events:</b> <b>{9}</b><br>
          <b>Type:</b> <b>{0}</b><br>
          <b>Namespace:</b> {1}<br>
          <b>Reason:</b> <b>{2}</b><br>
          <b>Message:</b> {3}<br>
          <b>Kind:</b> {4}<br>
          <b>Name:</b> {5}<br>
          <b>Count:</b> {6}<br>
          <b>First Timestamp:</b> {7}<br>
          <b>Last Timestamp:</b> {8}<br>
        alert_text_args:
        - kubernetes.event.type
        - kubernetes.event.involvedObject.namespace
        - kubernetes.event.reason
        - kubernetes.event.message
        - kubernetes.event.involvedObject.kind
        - kubernetes.event.involvedObject.name
        - kubernetes.event.count
        - kubernetes.event.firstTimestamp
        - kubernetes.event.lastTimestamp
        - num_hits
  elastalert-healthcheck-alert.yaml: |
    name: Elastalert Health Check

    type: frequency

    index: .all*

    num_events: 1

    realert:
      minutes: 30

    aggregation:
      minutes: 30

    timeframe:
      minutes: 1

    use_count_query: true
    doc_type: com.redhat.viaq.common

    filter:
    - query:
        match:
          level: info

    alert:
    - ms_teams:
        ms_teams_webhook_url: https://outlook.office.com/webhook/2a34a818-6745-4096-97bf-5b26caf63f7f@a8eec281-aaa3-4dae-ac9b-9a398b9215e7/IncomingWebhook/5e349056dee94949887b4625d70432f1/cb742064-a9b6-4b62-bb88-f7fe3a905112
        ms_teams_alert_summary: "Elastalert seems to be working fine."
        alert_subject: Elastalert Health Check
        alert_text: "Elastalert seems to be working fine."
        alert_text_type: alert_text_only
  kafka-prod-alert.yaml: |
    name: KAFKA-PROD - Error

    type: frequency

    index: .all*

    num_events: 1

    timeframe:
      minutes: 2

    filter:
    - query:
        bool:
          must:
          - match:
              kubernetes.namespace_name: kafka-prod
          - match:
              level: err

    alert:
    - ms_teams:
        ms_teams_webhook_url: https://outlook.office.com/webhook/2a34a818-6745-4096-97bf-5b26caf63f7f@a8eec281-aaa3-4dae-ac9b-9a398b9215e7/IncomingWebhook/5e349056dee94949887b4625d70432f1/cb742064-a9b6-4b62-bb88-f7fe3a905112
        alert_text_type: alert_text_only
        ms_teams_alert_summary: "At least one error level log entry found."
        alert_text: |
          <b>Pod Name:</b> <b>{0}</b><br>
          <b>Level:</b> <b>{1}</b><br>
          <b>No. of Hits:</b> {3}<br>
          <b>Message:</b> {2}<br>
        alert_text_args:
        - kubernetes.pod_name
        - level
        - message
        - num_hits
  nuadmit-alert.yaml: |
    name: NUADMIT - Error

    type: frequency

    index: .all*

    num_events: 1

    timeframe:
      minutes: 2

    filter:
    - query:
        bool:
          must:
          - match:
              kubernetes.namespace_name: nuadmit-prod
          - match:
              level: err

    alert:
    - ms_teams:
        ms_teams_webhook_url: https://outlook.office.com/webhook/0b590a01-3739-44be-8a19-5ad8414167f5@a8eec281-aaa3-4dae-ac9b-9a398b9215e7/IncomingWebhook/4c846f496acd42cb8aa44e42ccfcee2b/cb742064-a9b6-4b62-bb88-f7fe3a905112
        alert_text_type: alert_text_only
        ms_teams_alert_summary: "At least one error level log entry found."
        alert_text: |
          <b>Pod Name:</b> <b>{0}</b><br>
          <b>Level:</b> <b>{1}</b><br>
          <b>No. of Hits:</b> {3}<br>
          <b>Message:</b> {2}<br>
        alert_text_args:
        - kubernetes.pod_name
        - level
        - message
        - num_hits
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: elastalert-ocp
  name: elastalert-ocp
  namespace: openshift-logging
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: elastalert-ocp:latest
  source:
    git:
      uri: https://github.com/amolde/openshift-elastalert.git
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  successfulBuildsHistoryLimit: 5
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: elastalert-ocp
  namespace: openshift-logging
